version: "1.0"

services:
  db:
    container_name: cocktail_db_many_to_many
    image: postgres:15
    volumes:
      - ./init:/docker-entrypoint-initdb.d
    restart: always
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
